services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "8081:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./${DATABASE_NAME}:/app/dev.sqlite3 
      - .:/app  
    env_file: .env

volumes:
  sql-data:
