version: '3'

services:
  backend:
    build:
      context: .  # Context is the root of the project
      dockerfile: Dockerfile  # Dockerfile is in the root
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Mount the entire project so that changes are reflected
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: vue_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8081:8080"
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
