# Generated by Django 3.2.25 on 2024-10-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_transaction_products_transaction_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_retired',
            field=models.BooleanField(default=False),
        ),
    ]
